use oya_frontend::graph::{ExecutionState, Node, NodeCategory, NodeId, Viewport, Workflow};

pub fn default_workflow() -> Workflow {
    Workflow {
        nodes: vec![
            Node {
                id: NodeId::new(),
                name: "HTTP Handler".to_string(),
                description: "POST /SignupWorkflow/{userId}/run".to_string(),
                node_type: "http-handler".to_string(),
                category: NodeCategory::Entry,
                icon: "globe".to_string(),
                x: 350.0,
                y: 40.0,
                config: serde_json::json!({"configured": true, "status": "completed", "journalIndex": 0}),
                last_output: None,
                selected: false,
                executing: false,
                skipped: false,
                error: None,
                execution_state: ExecutionState::default(),
            },
            Node {
                id: NodeId::new(),
                name: "Durable Step".to_string(),
                description: "Create user in database".to_string(),
                node_type: "run".to_string(),
                category: NodeCategory::Durable,
                icon: "shield".to_string(),
                x: 350.0,
                y: 170.0,
                config: serde_json::json!({"configured": true, "status": "completed", "durableStepName": "create-user", "journalIndex": 1}),
                last_output: None,
                selected: false,
                executing: false,
                skipped: false,
                error: None,
                execution_state: ExecutionState::default(),
            },
            Node {
                id: NodeId::new(),
                name: "If / Else".to_string(),
                description: "Check if user creation succeeded".to_string(),
                node_type: "condition".to_string(),
                category: NodeCategory::Flow,
                icon: "git-branch".to_string(),
                x: 350.0,
                y: 300.0,
                config: serde_json::json!({"configured": true, "status": "completed", "journalIndex": 2}),
                last_output: None,
                selected: false,
                executing: false,
                skipped: false,
                error: None,
                execution_state: ExecutionState::default(),
            },
        ],
        connections: vec![],
        viewport: Viewport {
            x: 0.0,
            y: 0.0,
            zoom: 0.85,
        },
        execution_queue: vec![],
        current_step: 0,
        history: vec![],
    }
}
